### ISSUE TITLE
Error while running tool

### ISSUE THREAD

**Issue by john047** [ZupIT/horusec#1100]
**What happened**:
Error while running tool

**How to reproduce it (as minimally and precisely as possible)**:

```
horusec_sast:
  stage: check-code
  image: horuszup/horusec-cli:latest
  
  services:
  - docker:dind

  script:
    - horusec start -p ./ -o json -O horusec-report.json
   
   artifacts:
   paths:
     - horusec-report.json
   expire_in: 1h
```

```
time="2022-06-27T08:42:12Z" level=warning msg="{HORUSEC_CLI} During execution we found some problems:"
time="2022-06-27T08:42:12Z" level=error msg="{HORUSEC_CLI} Error while running tool DotnetCli: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /builds/maingroup/subgroup/project/.horusec/8d61c6b9-f012-4ad7-bad7-b8f893ef74c1"
time="2022-06-27T08:42:12Z" level=error msg="{HORUSEC_CLI} Error while running tool SecurityCodeScan: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /builds/maingroup/subgroup/project/.horusec/8d61c6b9-f012-4ad7-bad7-b8f893ef74c1"
time="2022-06-27T08:42:12Z" level=error msg="{HORUSEC_CLI} Error while running tool Semgrep: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /builds/maingroup/subgroup/project/.horusec/8d61c6b9-f012-4ad7-bad7-b8f893ef74c1"
time="2022-06-27T08:42:12Z" level=error msg="{HORUSEC_CLI} Error while running tool Trivy: trivy config cmd: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /builds/maingroup/subgroup/project/.horusec/8d61c6b9-f012-4ad7-bad7-b8f893ef74c1"
```

**Environment**:
- Horusec version (use `horusec version`):
Version: v2.8.0
Git commit: https://github.com/ZupIT/horusec/commit/df32c1ce03d2de748cecb76cff383f2851e198c3
Built: Wed Jun 08 13:57:08 2022
Distribution: normal

How to fix this problem?
