### ISSUE TITLE
Duvidas sobre parametrizações

### ISSUE THREAD

**Issue by GabrielMioranza** [ZupIT/horusec#369]
**What happened**:
Eu estou tentando subir a stack em um servidor, aqui utilizo o traefik como proxy reverso, adicionei as labels do meu proxy reverso e subi a stack utilizando `docker-compose -f deployments/docker-compose.yaml ` e tudo ocorreu sem erros, mas ao logar no manager, o mesmo não consegue autenticar com a api e o auth.

Gostaria de entender como alterar os endereços de comunicação entre os containers, visto que via console vi que está chamando em localhost (127.0.0.1:8006)

**Environment**:
- Horusec version (use `horusec version`):
latest
- Operating System:
- Ubuntu server 20.04
- 
- Network plugin / Tool and version (if this is a network-related / tool bug):
traefik as reverse proxy

**Comment by wiliansilvazup** [comment]
Bom dia @GabrielMioranza 
Como você subiu sua aplicação em outro host diferente de sua máquina local você precisa alterar a interface grafica do horusec para que ele relize a comunicação com este host.

# Como rodar a aplicação web em outro host?

É bastante comum realizar testes em um máquinas virtuais ou até mesmo mudar o host da sua máquina para conhecer uma aplicação, no Horusec você tem a possibilidade de realizar um teste rápido para entender como aplicação trabalhar e como adequa-la ao seu ambiente de trabalho. Mas quais passos devo seguir?

##### O primeiro passo é você realizar a instalação da aplicação web do horusec em seu ambiente geramente via docker compose rodando o comando `make install`. Após instalada você terá todos seus containers rodando e prontos para serem utilizados.

Após instalar você pode perceber que alguns serviços por padrão **não são inciados** como por exemplo o Horusec-Messages e o Horusec-Webhook. Isto é devido ao serviço de mensageria esta configurado para estar desabilitado por padrão.

##### Tentei acessar o Horusec-Manager através do meu navegador em minha maquina, mas não apareceu nenhum resultado o que fazer?

Quando você sobe a aplicação e tenta acessar através de um host desconhecido o horusec por padrão sempre tenta realizar a comunicação através do ip `127.0.0.1` com isso a comunicação entre os serviços sempre será localmente. Quando você muda o host da sua máquina ou instala a aplicação em uma máquina virtual é necessário configurar o Horusec-Manager para que ele entenda o destino onde está as aplicações que você hospedou. Para isto vá no serviço e altere suas variáveis de ambiente e reinicie a aplicação.

Quando você realiza o comando `make install` ele executa o [docker-compose.yaml](https://github.com/ZupIT/horusec/blob/master/deployments/docker-compose.yaml) padrão do Horusec, o Horusec-Manager está sendo executado com a seguinte configuração
```yaml
...
  horusec-manager:
    image: horuszup/horusec-manager:latest
    restart: always
    container_name: horusec-manager
    ports:
      - "8043:8080"
    environment:
      REACT_APP_HORUSEC_ENDPOINT_API: ${REACT_APP_HORUSEC_ENDPOINT_API}
      REACT_APP_HORUSEC_ENDPOINT_ANALYTIC: ${REACT_APP_HORUSEC_ENDPOINT_ANALYTIC}
      REACT_APP_HORUSEC_ENDPOINT_ACCOUNT: ${REACT_APP_HORUSEC_ENDPOINT_ACCOUNT}
      REACT_APP_HORUSEC_ENDPOINT_AUTH: ${REACT_APP_HORUSEC_ENDPOINT_AUTH}
...
```

então basta você exportar as variáveis referente aos serviços e onde estão sendo hospedados e instalar novamente o horusec, para este cenário seria:
```bash
export REACT_APP_HORUSEC_ENDPOINT_API="http:\/\/YOUR_HOST:8000" && \
export REACT_APP_HORUSEC_ENDPOINT_ANALYTIC="http:\/\/YOUR_HOST:8005" && \
export REACT_APP_HORUSEC_ENDPOINT_ACCOUNT="http:\/\/YOUR_HOST:8003" && \
export REACT_APP_HORUSEC_ENDPOINT_AUTH="http:\/\/YOUR_HOST:8006" && \
make install
```
