### ISSUE TITLE
horusec-cli from within Kubernetes DinD container consistently reports no issues 

### ISSUE THREAD

**Issue by ccureau** [ZupIT/horusec#894]
**What happened**:

A Kubernetes pod with a simple Docker-in-Docker setup fails to report vulnerabilities from either a docker-based scan or the `horusec-cli` tool. This happens regardless of the state of the `-D` flag being set to `true` or `false`.

**What you expected to happen**:

When I run this on a Mac with Docker Desktop installed, the scan reports vulnerabilities.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a deployment with a `docker` and `docker-socket` container

```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: horusec
  name: horusec
spec:
  containers:
  - image: docker:20.10.11
    name: docker
    command:
    - sleep
    args:
    - '99d'
    resources: {}
    volumeMounts:
    - name: varrun
      mountPath: /var/run
  - image: docker:20.10.11-dind
    securityContext:
      privileged: true
    name: docker-daemon
    resources: {}
    volumeMounts:
    - name: varrun
      mountPath: /var/run
  volumes:
  - name: varrun
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
```

2.  in the `docker` container, execute a docker scan against some code

`docker run --rm -v /var/run/docker.sock:/var/run/docker.sock -v ${PWD}:/workspace horuszup/horusec-cli:v2.6 horusec start '-p=/workspace/' '-P=${PWD}' '-o=sonarqube' '-O=/workspace/horusec.json'`

**Anything else we need to know?**:

Regardless of whether I run a docker-based scan or a scan from the `horusec-cli` tool (both with and without `-D="true"`) the scan always reports no vulnerabilities found

**Environment**: Kubernetes (1.18+)
- Horusec version (use `horusec version`): v2.6.7
- Operating System: Linux
- Network plugin / Tool and version (if this is a network-related / tool bug):
- Others:
